[build]
  command = "ng build"
  publish = "dist/QRT/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

# Excluir rutas dinámicas de prerender
[plugins.inputs]
  prerender = true
  exclude = ["acceso/:token"]
